// APP ACTIONS
export const SET_BASE_PATH = "SET_BASE_PATH";

// MOVIE PAGE ACTIONS
export const FILL_MOVIES = "FILL_MOVIES";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";
