// APP ACTIONS
export const SET_BASE_PATH = "SET_BASE_PATH";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const SET_TOTAL_PAGES = "SET_TOTAL_PAGES";

// MOVIE PAGE ACTIONS
export const FILL_MOVIES = "FILL_MOVIES";

// SERIES PAGE ACTIONS
export const FILL_SERIES = "FILL_SERIES";
